import React from 'react';
import { X, Copy, Database, Check, Box, Settings, AlertTriangle } from 'lucide-react';

interface DatabaseSetupProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DatabaseSetup: React.FC<DatabaseSetupProps> = ({ isOpen, onClose }) => {
  const [copiedStorage, setCopiedStorage] = React.useState(false);

  if (!isOpen) return null;

  const storageSql = `-- 1. יצירת התיקיות (Buckets) והגדלת נפח העלאה
-- הגדלנו את המגבלה ל-100MB (104857600 Bytes)
INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('hub-content', 'hub-content', true, 104857600)
ON CONFLICT (id) DO UPDATE SET file_size_limit = 104857600;

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('product-images', 'product-images', true, 10485760)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit) 
VALUES ('product-files', 'product-files', true, 104857600)
ON CONFLICT (id) DO NOTHING;

-- 2. עדכון טבלת hub_videos והוספת טבלת תגובות לסרטונים
ALTER TABLE public.hub_videos ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.hub_video_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES public.hub_videos(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name TEXT,
  user_avatar TEXT,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. הגדרת מדיניות אבטחה (RLS)
BEGIN;
  -- Storage RLS
  DROP POLICY IF EXISTS "Admin can upload hub content" ON storage.objects;
  DROP POLICY IF EXISTS "Anyone can view hub content" ON storage.objects;
  DROP POLICY IF EXISTS "Admin can manage hub objects" ON storage.objects;

  CREATE POLICY "Admin can upload hub content" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'hub-content' AND (auth.jwt() ->> 'email') = 'alexivanov4425@gmail.com');
  CREATE POLICY "Anyone can view hub content" ON storage.objects FOR SELECT USING ( bucket_id = 'hub-content' );
  CREATE POLICY "Admin can manage hub objects" ON storage.objects FOR ALL USING (bucket_id = 'hub-content' AND (auth.jwt() ->> 'email') = 'alexivanov4425@gmail.com');

  -- Video Comments RLS
  ALTER TABLE public.hub_video_comments ENABLE ROW LEVEL SECURITY;
  DROP POLICY IF EXISTS "Anyone can view hub comments" ON public.hub_video_comments;
  DROP POLICY IF EXISTS "Authenticated can post hub comments" ON public.hub_video_comments;
  
  CREATE POLICY "Anyone can view hub comments" ON public.hub_video_comments FOR SELECT USING (true);
  CREATE POLICY "Authenticated can post hub comments" ON public.hub_video_comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');
COMMIT;

-- 4. עדכון הרשאות לטבלת הסרטונים (hub_videos)
BEGIN;
  DROP POLICY IF EXISTS "Admin can manage videos" ON public.hub_videos;
  CREATE POLICY "Admin can manage videos" ON public.hub_videos FOR ALL USING ( (auth.jwt() ->> 'email') = 'alexivanov4425@gmail.com' ) WITH CHECK ( (auth.jwt() ->> 'email') = 'alexivanov4425@gmail.com' );
COMMIT;`;

  const handleCopy = (text: string, setFn: (v: boolean) => void) => {
    navigator.clipboard.writeText(text);
    setFn(true);
    setTimeout(() => setFn(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center p-4" dir="ltr">
      <div className="absolute inset-0 bg-[#020617]/95 backdrop-blur-md" onClick={onClose}></div>
      <div className="relative w-full max-w-2xl bg-[#0F172A] border border-[#334155] rounded-3xl shadow-2xl flex flex-col max-h-[90vh] overflow-hidden animate-fadeIn">
        <div className="p-6 bg-[#1E293B] border-b border-[#334155] flex items-center justify-between">
            <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-500/10 rounded-lg border border-blue-500/20">
                    <Settings size={20} className="text-blue-400" />
                </div>
                <div>
                    <h2 className="text-lg font-bold text-white">הגדרות בסיס נתונים ואחסון</h2>
                    <p className="text-xs text-[#94A3B8]">תיקון שגיאות RLS והגדלת נפח העלאה</p>
                </div>
            </div>
            <button onClick={onClose} className="text-[#94A3B8] hover:text-white">
                <X size={24} />
            </button>
        </div>
        <div className="p-6 overflow-y-auto custom-scrollbar bg-[#0F172A] space-y-6" dir="rtl">
            <div className="bg-amber-500/10 border border-amber-500/20 rounded-2xl p-5">
                <div className="flex items-center gap-2 mb-3 text-amber-400">
                    <AlertTriangle size={20} />
                    <h3 className="font-bold">פתרון בעיית נפח העלאה (File Size)</h3>
                </div>
                <p className="text-sm text-amber-200/80 mb-4 leading-relaxed">
                    אם אתה מקבל שגיאה שהקובץ גדול מדי, עליך להריץ את ה-SQL למטה. <br/>
                    <strong>הסקריפט מגדיל את המגבלה ב-hub-content ל-100MB ויוצר טבלת תגובות.</strong>
                </p>
            </div>
            <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-2xl p-4">
                <div className="flex items-start justify-between mb-3" dir="ltr">
                   <button 
                        onClick={() => handleCopy(storageSql, setCopiedStorage)}
                        className="flex items-center gap-2 px-3 py-1 bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/30 rounded-lg text-xs font-bold text-emerald-300 transition-all"
                    >
                        {copiedStorage ? <Check size={14} /> : <Copy size={14} />}
                        {copiedStorage ? 'Copied' : 'Copy SQL'}
                    </button>
                   <div className="flex items-center gap-2 text-right">
                       <h3 className="text-emerald-400 font-bold text-sm">תיקון הרשאות והגדלת נפח (SQL)</h3>
                       <Box size={16} className="text-emerald-400" />
                   </div>
                </div>
                <pre className="bg-[#020617] border border-emerald-900/30 rounded-xl p-3 text-[10px] font-mono text-emerald-200 overflow-x-auto h-64 custom-scrollbar" dir="ltr">
                    {storageSql}
                </pre>
            </div>
            <div className="p-4 border-t border-[#334155] flex justify-end">
                <button onClick={onClose} className="px-8 py-3 bg-white text-black font-bold rounded-xl hover:bg-gray-200 transition-colors text-sm">סגור</button>
            </div>
        </div>
      </div>
    </div>
  );
};